<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $customers = [
            [
                'first_name' => 'Ali',
                'last_name' => 'Ahmed',
                'email' => 'ali@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Ali',
                'remarks' => 'Remarks For Ali',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Abdul',
                'last_name' => 'Subhan',
                'email' => 'subhan@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Subhan',
                'remarks' => 'Remarks For Subhan',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Ahmed',
                'last_name' => 'Ali',
                'email' => 'ahmed@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Ahmed',
                'remarks' => 'Remarks For Ahmed',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Haris',
                'last_name' => 'Ali',
                'email' => 'haris@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Haris',
                'remarks' => 'Remarks For Haris',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'kamran',
                'last_name' => 'Ahmed',
                'email' => 'kamran@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Kamran',
                'remarks' => 'Remarks For Kamran',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
            [
                'first_name' => 'Farhan',
                'last_name' => 'Ahmed',
                'email' => 'farhan@gmail.com',
                'phone_number' => '0321554414',
                'phone_number2' => '02585541',
                'phone_number3' => '02345511',
                'cnic' => '7845961120251',
                'cnic_pic' => 'profile-1655770404',
                'location_pic' => 'profile-1655770404',
                'address' => 'abc road xyz city pqrs',
                'address2' => '',
                'location' => '',
                'location2' => '',
                'agreement' => 'agreement to Farhan',
                'remarks' => 'Remarks For Farhan',
                'reference' => 'abc',
                'dealer' => 'xyz',
                'dealer_cnic' => '452505612206',
                'proprietor' => 'pqrs',
                'proprietor_cnic' => '7484551151251',
                'is_owner' => 1,
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ],
        ];
    
        Customer::insert($customers);
    }
}
